name: update

permissions:
  contents: write

on:
  push:
  schedule:
    - cron:  '0 0 * * *'
  pull_request:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-24.04
    name: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install
        run: |
          sudo apt-get update
          sudo apt-get install -y zip jq

      - name: build
        id: build
        run: |
         bash ./build.sh ladybird-js-Linux-x86_64 ladybird-js-Linux-x86_64 x86_64-unknown-linux-gnu ${{ secrets.GITHUB_TOKEN }}
         bash ./build.sh ladybird-js-macOS-arm64 ladybird-js-macOS-arm64 aarch64-apple-darwin ${{ secrets.GITHUB_TOKEN }}

         #  bash ./build.sh ladybird-js-macOS-universal2 ladybird-js-macOS-arm64 x86_64-apple-darwin ${{ secrets.GITHUB_TOKEN }}

      - name: release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.build.outputs.tag }}
          artifacts: "*.zip"
          allowUpdates: true
  test-release:
    needs: ["build"]
    strategy:
      matrix:
        os: [
          ubuntu-24.04,
          macos-14,
          # macos-13
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: wait
        run: |
          sleep 120
      - uses: easy-install/easy-setup@v1
        with:
          url: https://github.com/ahaoboy/ladybird-js-build
      - name: test
        run: |
          which js
          echo "console.log(1+1)" >> ./test.js
          js ./test.js
